### ISSUE TITLE
ScrollViewer

### ISSUE THREAD

**Issue by Xopoko** [youngytj/uwp_PullToRefreshListview#1]
How can I use it with the usual ScrollView?

**Comment by youngytj** [comment]
Sorry, Can not add the control in a ScrollViewer. Maybe you can try this[PullToRefreshUWP_WindowsComposition](https://github.com/JustinXinLiu/PullToRefreshUWP_WindowsComposition) since my project has a bad performance.

**Comment by Xopoko** [comment]
Thanks for the help.
